pitz: new package
pitz is a distributed bug tracker, inspired by ditz. Homepage:
http://pitz.tplus1.com/

pitz has a command line interface, pitz-<command>, and a webapp,
pitz-webapp.

TODO: pitz has a pitz-shell utility that depends on ipython, but when I
enabled it it raised an exception. I think it depends on an old IPython
version:

  from IPython.Shell import IPShellEmbed
  ImportError: No module named Shell

A broken pitz-shell doesn't affect the rest of the command line
interface nor the webapp, so it is not critical to have it working.

There are not many distributed bug trackers out there, so I hope that
adding pitz to nixpkgs may inspire people to support pitz (or similar
software).