Fix Nixpkgs evaluation
The evaluation of liferea causes an error:

  error: assertion failed at `/tmp/nix-build-nixpkgs-tarball-1.0pre28992_1628c03.drv-0/git-export/pkgs/desktops/gnome-2/desktop/libgweather/default.nix:4:1'

Why this happens is a mystery, since liferea doesn't depend on
libgweather.  The problem can be reproduced by evaluating:

  builtins.toXML (import <nixpkgs> { system = "x86_64-darwin"; }).liferea

It seems to have something to do with builderDefs magic in webkit_gtk2.

http://hydra.nixos.org/build/6039089