pakcs: Disable in Hydra because the build doesn't terminate
It appears to loop saying:

ERROR: load_files/2: No permission to load source `/tmp/nix-build-pakcs-1.10.0.drv-1/pakcs/lib/.curry/pakcs/Prelude.pl' (Non-module file already loaded into module prologbasics; trying to load into user)

http://hydra.nixos.org/build/4760096