jitsi: fix when installed via systemPackages
Close #9754.
Otherwise, the wrong directory is changed into, and trying to start Jitsi gives:

$ jitsi
Error: Could not find or load main class net.java.sip.communicator.launcher.SIPCommunicator