flightgear: 2.10.0 -> 2.12.0 (and make it run again)
The current FlightGear expression doesn't work:

  bash$ nix-build -A flightgear
  /nix/store/3c47sibzb9h1vhnn0gnh692hkpjc5p5v-flightgear-2.10.0

  bash$ ./result/bin/fgfs
  ERROR: The path '/nix/store/3c47sibzb9h1vhnn0gnh692hkpjc5p5v-flightgear-2.10.0/lib/FlightGear' does not exist in the file system.

  Base package check failed:
    Version [none] found at: /nix/store/3c47sibzb9h1vhnn0gnh692hkpjc5p5v-flightgear-2.10.0/lib/FlightGear
    Version 2.10.0 is required.
  Please upgrade/downgrade base package and set the path to your fgdata
  with --fg-root=path_to_your_fgdata

We could probably make the 2.10.0 version run, but I had already
upgraded it to 2.12.0 before I made it work. It seems only the data dir
configuration was wrong/missing: FG_DATA_DIR="$out/share/FlightGear/".

Simgear must be in version sync with flightgear, hence the upgrade.

Most of the diff is because I rewrote the flightgear expression to what
I think is the "new style". I wanted to add a preConfigure phase but
didn't understand why this expression had custom phases. So I just
rewrote the whole thing to something I consider more readable.