lie: only build on linux
Darwin build fails from conflicts in libSystem:

In file included from altdom.c:1:
In file included from /private/var/folders/7t/4vz31njj37b8y_bg6z3t7tk00000gn/T/nix-build-LiE-2.2.2.drv-0/LiE/lie.h:34:
In file included from /nix/store/9ll4m9yx854hr64fn1w9ra3qimm3pzdk-Libsystem-osx-10.9.5/include/string.h:176:
/nix/store/9ll4m9yx854hr64fn1w9ra3qimm3pzdk-Libsystem-osx-10.9.5/include/strings.h:73:7: error: redefinition of 'index' as different kind of symbol
char    *index(const char *, int) __POSIX_C_DEPRECATED(200112L);
         ^
/private/var/folders/7t/4vz31njj37b8y_bg6z3t7tk00000gn/T/nix-build-LiE-2.2.2.drv-0/LiE/lie.h:6:14: note: previous definition is here
typedef long index;
             ^
1 error generated.