rtl8723bs: 6918e9b2ff29 -> 2016-04-11, fix build against 4.7
Upstream
https://github.com/hadess/rtl8723bs/commit/e71a5fc58c3a1092805c69e7bccb5ab2f6da38f9
adds linux 4.7 support; all subsequent commits are error fixes so we
bump to current HEAD for good measure.

Built against linux and linux_latest.

Mark as broken on -grsec, seems incompatible with PaX
constification:
> 76fb2-src/hal/rtl8723b_hal_init.c:2186:26: error: assignment of member
'free_hal_data' in read-only object
  pHalFunc->free_hal_data = &rtl8723b_free_hal_data;

and so on.