duplicity: add dependency on rsync
When using the rsync:// protocol, duplicity expects to find the rsync binary in the path.
Without rsync in the path, duplicity fails with the following error

    Attempt 1 failed. AttributeError: 'NoneType' object has no attribute 'rfind'

Adding rsync to the path enables the rsync:// protocol to work correctly.

(cherry picked from commit 8df0bb7aac42c78dbd8e2fd9bd600cbd714f3f1c)