nixos/redis: fix evaluation
Commit 89fee1006c03d40052842b49f5cdbbeb755d081b ("nixos/redis: clean up
option types") broke nixos evaluation:

  error: attempt to call something which is not a function but a set, at .../nixpkgs/nixos/modules/services/databases/redis.nix:111:28

Fix it.

Reported by Oliver Charles (thanks!).