Fix eval
Fixes this:

$ nix-env -f . -qa \* --meta --xml --drv-path --show-trace >/dev/null
...
error: while querying the derivation named ‘pypy2.5-graph-tool-2.2.36’:
while evaluating the attribute ‘preConfigure’ of the derivation ‘pypy2.5-graph-tool-2.2.36’ at "/home/bfo/nixpkgs/pkgs/development/python-modules/graph-tool/2.x.x.nix":5:3:
attribute ‘sitePackages’ missing, at "/home/bfo/nixpkgs/pkgs/development/python-modules/graph-tool/2.x.x.nix":22:54